config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations"
  }
  devise_scope :user do
    get '/users/complete_link', :to => 'users/registrations#complete_link'
    post '/users/complete_link', :to => 'users/registrations#create_link'
  end

  #
  root 'home#index'
  match '/home/index' => 'home#index', :via => [:get, :post]

  #
  match '/entries' => 'entries#show_list', :via => :get
  match '/entries/:entry_id' => 'entries#show_entry', :via => :get

  #
  match '/users' => 'users#index', :via => :get
  match '/users/codes' => 'users#show_my_codes', :via => :get

  # system
  match '/api/system/source' => 'api#post_source', :via => :post
  match '/api/system/entry/:entry_id' => 'api#get_entry', :via => :get
  match '/api/system/ticket/:ticket_id' => 'api#get_ticket', :via => :get

  # public api
  match '/api/nodes' => 'api#get_cage_nodes', :via => :get

  #
  match '/about' => 'about#index', :via => :get

  # for master controller(like dashboard for admin)
  match '/master' => 'master#index', :via => :get
  match '/master/users' => 'master#list_users', :via => :get
  match '/master/users/:user_id' => 'master#delete_user', :via => :delete
  match '/master/update_proctable' => 'master#update_proctable', :via => :post
  match '/master/runner_node_addresses' => 'master#update_node_addresses', :via => :post
  match '/master/enable_langproc/:proc_id' => 'master#enable_langproc', :via => :post
  match '/master/disable_langproc/:proc_id' => 'master#disable_langproc', :via => :post

  #
  match '/feedback/send' => 'feedback#send_mail', :via => :post

  match '/404', to: 'application#error_404', via: :all
  match '/422', to: 'application#error_422', via: :all
  match '/50x', to: 'application#error_50x', via: :all

  unless Rails.env.development?
    match "/*path", to: 'application#error_404', via: :all
  end
end

app/models/entry.rb
class Entry
  include Mongoid::Document
  include Mongoid::Timestamps

  field :owner_user_id, :type => String, :default => nil
  field :revision, :type => String, :default => ""
  field :visibility, :type => Integer
  has_many :codes
  has_many :tickets

  field :tags, :type => Array, :default => []
  field :language_tags, :type => Array, :default => []
  field :viewed_count, :type => Integer, :default => 0
end


class Code
  include Mongoid::Document
  belongs_to :entry, :inverse_of => :codes

  field :file_id
  field :file_name, :type => String
  field :type, :type => Symbol  # :native, :gist

  def source_code(encoding = :utf8)
    code = case self.type
           when :native
             g = Mongoid::GridFs.get(self.file_id)
             g.data

           else
             raise NotSupported.new
           end

    case encoding
    when :utf8
      code.force_encoding('utf-8')
    end

    return code
  end
end


class Ticket
  include Mongoid::Document
  belongs_to :entry, :inverse_of => :tickets

  field :index, :type => Integer

  field :is_running, :type => Boolean
  field :processed, :type => Boolean

  field :do_execute, :type => Boolean
  field :proc_id, :type => Integer
  field :proc_version, :type => String
  field :proc_label, :type => String

  field :phase, :type => Integer

  embeds_one :compile_state
  embeds_one :link_state
  embeds_many :run_states   # NOTE: NOT ordered by execution order
end


class State
  include Mongoid::Document

  field :index, :type => Integer

  field :used_cpu_time_sec, :type => Float
  field :used_memory_bytes, :type => Integer
  field :signal, :type => Integer
  field :return_code, :type => Integer
  field :command_line, :type => String
  field :status, :type => Integer
  field :system_error_message, :type => String

  field :structured_command_line, :type => Array
  field :cpu_time_sec_limit, :type => Float
  field :memory_bytes_limit, :type => Integer

  field :out, :type => Array
  field :err, :type => Array
end

class CompileState < State
  embedded_in :ticket, :inverse_of => :compile_state
end

class LinkState < State
  embedded_in :ticket, :inverse_of => :link_state
end

class RunState < State
  embedded_in :ticket, :inverse_of => :run_states
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  #
  def show_list
    filtered_entry = if params[:query].nil? then
                       Entry.all
                     else
                       # do NOT distinguish Upper/Lower camel
                       Entry.in( language_tags: /#{Regexp.escape(params[:query])}/i )
                     end

    permission_filtered_entry = if user_signed_in? then
                                  if can? :manage, :all
                                    filtered_entry
                                  else
                                    # public OR own entry
                                    filtered_entry.any_of( { owner_user_id: current_user.id },
                                                           { visibility: 0 } )   # visibility means PUBLIC
                                  end
                                else
                                  # public
                                  filtered_entry.where( visibility: 0 )   # visibility means PUBLIC
                                end

    #
    @entries_only = permission_filtered_entry.desc( :id ).page( params[:page] ).per( 16 )

    @entries = @entries_only.map do |e|
      next {
        entry: e,
        user: User.where( id: e.owner_user_id ).first
      }
    end
  end

  class HasNoPermission
  end
  class NotSupported
  end

  ########################################
  #
  def show_entry
    @entry_id = params[:entry_id].to_s
    if @entry_id == "!search"
      return redirect_to :action => "show_list", :query => params[:query]
    end

    @entry = Entry.find(@entry_id)

    # check visibility
    if @entry["visibility"] == 2    # PRIVATE
      if user_signed_in? then
        if can? :manage, :all
          # pass
        else
          raise HasNoPermission.new unless @entry['owner_user_id'].to_s == current_user.id.to_s
        end
      else
        raise HasNoPermission.new
      end
    end

    codes = @entry.codes
    @filenames = codes.map do |c|
      c.file_name
    end

    grid_fs = Mongoid::GridFs
    @source_codes = codes.map do |c|
      case c.type
      when :native
        g = grid_fs.get(c.file_id)
        g.data

      else
        raise NotSupported.new
      end
    end

  rescue Mongoid::Errors::DocumentNotFound
    render :action => "not_found", :status => 404

  rescue HasNoPermission
    render :action => "not_permitted", :status => 403

  end


  ########################################
  #
  def not_found
  end


  ########################################
  #
  def not_permitted
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_main_container.html.erb
<div class="container-fluid has-no-extra-space">
    <!-- editor container -->
    <div id="sc-code-editor-ctrl" class="row" ng-controller="SourceCodeEditor">
        <div class="col-sm-12 has-no-extra-space">
            <div class="well well-sm">
                <div class="container-fluid has-no-extra-space">
                    <%= render :partial => '_common/editor_options' %>
                    <%= render :partial => '_common/editor_core', :locals => {
                        source_codes: @source_codes,
                        readonly: true
                    } %>
                </div>
            </div>
        </div>
    </div>
    <!-- /editor container -->


    <!-- operator container -->
    <div class="row" id="tickets-row">
        <!-- tickets tabs -->
        <div class="col-sm-12 has-no-extra-space">
            <div class="well well-sm">
                <%= render :partial => '_common/tabset', :locals => {
                    entry_id: @entry_id,
                    with_init: true,
                    readonly: true
                } %>
            </div>
        </div>
        <!-- /tickets tabs -->
    </div>
    <!-- /operator container -->
</div>

<% if false %>
    <!-- sidebar container -->
    <div class="col-sm-2" style="position:relative;">
        <div class="well well-sm sc-sidebar affix" id="sc-navbar">
            <ul class="nav nav-pills nav-stacked sc-nav">
                <li><a href="#sc-code-editor-ctrl">Source Code</a></li>
                <li><a href="#tickets-row">Results</a></li>
            </ul>
        </div><!--/.well -->
    </div><!--/span-->
<% end %>

app/views/entries/_sub_container.html.erb
<div class="container-fluid has-no-extra-space">
    <div class="row">
        <div class="col-sm-12 has-no-extra-space0">

            <!-- clone -->
            <%= form_tag( '/home/index', :method => :post) do %>
                <input type='hidden'
                       id='entry_id'
                       name='entry_id'
                       value='<%= @entry_id %>'>
                <button type='submit'
                        class='btn btn-success'
                        style="width: 100%">
                    <strong>Clone!</strong>
                </button>
            <% end %>

            <h6>Visibility:</h6>
            <h6>
                <span class="glyphicon glyphicon-globe" ng-if="visibility == 0"></span>
                <span class="glyphicon glyphicon-eye-close" ng-if="visibility == 1"></span>
                <span class="glyphicon glyphicon-minus-sign" ng-if="visibility == 2"></span>
                <strong>{{['Public', 'Protected', 'Private'][visibility]}}</strong>
            </h6>

            <%# owner %>
            <% unless @entry['owner_user_id'].nil? %>
                <h6>Posted by:</h6>
                <h6>
                    <% user = User.where( id: @entry['owner_user_id'] ).first %>
                    <strong><%= user.name unless user.nil? %></strong>
                </h6>
            <% end %>

            <%# date %>
            <% unless @entry['created_at'].nil? %>
                <h6>Created at:</h6>
                <h6>
                    <strong><%= @entry['created_at'] %></strong>
                </h6>
            <% end %>

            <div id="custom-tweet-button" ng-if="current_entry_id !== null">
                <iframe allowtransparency="true"
                        frameborder="0"
                        scrolling="no"
                        ng-src="{{current_entry_tweet}}"
                        style="width:130px; height:20px;">
                </iframe>
            </div>

            <!-- /submit -->
        </div>
    </div>
</div>

app/views/entries/not_found.html.erb
<div class="jumbotron">
    <h2><span class="glyphicon glyphicon-remove"></span> Entry not found.</h2>
</div>

app/views/entries/not_permitted.html.erb
<div class="jumbotron">
    <h2><span class="glyphicon glyphicon-minus-sign"></span> This is privete entry.</h2>
</div>

app/views/entries/show_entry.html.erb
<div class="container-fluid ng-scope has-no-extra-space" ng-controller="EntryController">
    <div class="row has-no-extra-space">
        <!-- editor/input container -->
        <div class="col-sm-11 has-no-extra-space">
            <%= render :partial => 'main_container' %>
        </div>
        <!-- /editor/input container -->

        <!-- mini container -->
        <div class="col-sm-1 has-no-extra-space">
            <%= render :partial => 'sub_container' %>
        </div>
        <!-- /mini container -->
    </div>
</div>

app/views/entries/show_list.html.erb
<div class="container">

    <div class="row">
        <div class="col-sm-6">
            <%= paginate @entries_only %>
        </div>
        <div class="col-sm-2">
            <p class="text-right">
                <span class="glyphicon glyphicon-file"><%= Entry.count %>Entries</span>
            </p>
        </div>
        <div class="col-sm-4">
            <%= form_tag "/entries/!search", method: :get do %>
                <div class="input-group input-group-sm">
                    <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
                    <%= text_field_tag "query", params[:query], { :class => 'form-control', :placeholder => "language" } %>
                    <span class="input-group-btn">
                        <%= submit_tag "Search", { :name => nil, :class => 'btn btn-default' } %>
                    </span>
                </div>
            <% end %>
        </div>
    </div>


    <div class="row">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>EntryID</th>
                    <th>Language</th>
                    <th>Created at</th>
                    <th>Visibility</th>
                    <th>User</th>
                </tr>
            </thead>

            <tbody>
                <% @entries.each do |entry| %>
                    <tr data-link="<%= entries_path() %>">
                        <td>
                            <%= link_to "##{entry[:entry].id}", "/entries/#{entry[:entry].id}" %>
                        </td>

                        <td>
                            <%= entry[:entry].language_tags.join(' / ') unless entry[:entry].language_tags.nil? %>
                        </td>

                        <td>
                            <%= distance_of_time_in_words_to_now( entry[:entry].created_at ) unless entry[:entry].created_at.nil? %> ago
                        </td>

                        <td>
                            <% case entry[:entry].visibility %>
                            <% when 0 %>
                            <span class="glyphicon glyphicon-globe"></span> Public

                            <% when 1 %>
                            <span class="glyphicon glyphicon-eye-close"></span> Protected

                            <% when 2 %>
                            <span class="glyphicon glyphicon-minus-sign"></span> Private

                <% end %>
                        </td>


                        <td>
                            <% unless entry[:user].nil? %>
                                <%= entry[:user].name unless entry[:user].nil? %>
                            <% else %>
                                <small>(anon)</small>
                            <% end %>
                        </td>
                    </tr>
                    <% end %>
            </tbody>

        </table>
    </div>

    <div class="row">
        <%= paginate @entries_only %>
    </div>

</div>